// src/components/SocialCardGenerator.jsx
import React from 'react';
import { Download, Share2 } from 'lucide-react';

const SocialCardGenerator = ({ formData, results }) => {
  const generateImage = async () => {
    // Use html2canvas or similar library
    // For now, we'll create a downloadable text card
    const canvas = document.createElement('canvas');
    canvas.width = 1200;
    canvas.height = 630;
    const ctx = canvas.getContext('2d');

    // Background gradient
    const gradient = ctx.createLinearGradient(0, 0, 1200, 630);
    gradient.addColorStop(0, '#1e1b4b');
    gradient.addColorStop(1, '#7e22ce');
    ctx.fillStyle = gradient;
    ctx.fillRect(0, 0, 1200, 630);

    // Title
    ctx.fillStyle = '#ffffff';
    ctx.font = 'bold 60px Arial';
    ctx.fillText('GTA Online Assessment', 80, 120);

    // Tier
    ctx.font = 'bold 120px Arial';
    const tierColors = {
      S: '#fbbf24',
      'A+': '#34d399',
      A: '#60a5fa',
      B: '#a78bfa',
      C: '#f87171',
      D: '#9ca3af',
    };
    ctx.fillStyle = tierColors[results.tier] || '#ffffff';
    ctx.fillText(`Tier ${results.tier}`, 80, 280);

    // Score
    ctx.font = 'bold 40px Arial';
    ctx.fillStyle = '#e2e8f0';
    ctx.fillText(`Score: ${results.score}/100`, 80, 350);

    // Income
    ctx.fillText(`Income: $${(results.incomePerHour / 1000).toFixed(0)}k/hr`, 80, 410);

    // Rank
    ctx.fillText(`Rank ${formData.rank}`, 80, 470);

    // Footer
    ctx.font = '24px Arial';
    ctx.fillStyle = '#94a3b8';
    ctx.fillText('Generated by GTA Assessment Tool', 80, 580);

    // Download
    const url = canvas.toDataURL('image/png');
    const a = document.createElement('a');
    a.href = url;
    a.download = `gta-assessment-tier-${results.tier}.png`;
    a.click();
  };

  const shareText = `I'm Tier ${results.tier} in GTA Online! (Score: ${results.score}/100, $${(results.incomePerHour / 1000).toFixed(0)}k/hr income) 🎮💰`;

  const copyToClipboard = () => {
    navigator.clipboard?.writeText(shareText);
    alert('Share text copied to clipboard!');
  };

  return (
    <div className="bg-slate-900/60 border border-blue-500/30 rounded-2xl p-6 mb-6">
      <div className="flex items-center justify-between mb-4">
        <h3 className="text-xl font-bold text-white flex items-center gap-2">
          <Share2 className="w-6 h-6 text-blue-400" />
          Share Your Progress
        </h3>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-3">
        <button
          onClick={generateImage}
          className="px-4 py-3 bg-gradient-to-r from-purple-600 to-blue-600 hover:from-purple-500 hover:to-blue-500 text-white rounded-lg transition-all flex items-center justify-center gap-2 font-semibold"
        >
          <Download className="w-5 h-5" />
          Download Share Card
        </button>
        <button
          onClick={copyToClipboard}
          className="px-4 py-3 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-all flex items-center justify-center gap-2 font-semibold border border-slate-600"
        >
          <Share2 className="w-5 h-5" />
          Copy Share Text
        </button>
      </div>

      <div className="mt-4 p-3 bg-black/30 rounded-lg">
        <div className="text-xs text-slate-400 mb-1">Preview:</div>
        <div className="text-sm text-slate-200 italic">
          {shareText}
        </div>
      </div>
    </div>
  );
};

export default SocialCardGenerator;
