const DEFAULT_NIGHTCLUB_SOURCES = {
  imports: false,
  cargo: false,
  pharma: false,
  sporting: false,
  cash: false,
  organic: false,
  printing: false,
};

const DEFAULT_PURCHASE_DATES = {
  kosatka: null,
  sparrow: null,
  agency: null,
  nightclub: null,
  acidLab: null,
  bunker: null,
  autoShop: null,
  salvageYard: null,
};

const DEFAULT_NIGHTCLUB_STORAGE = {
  hasPounder: false,
  hasMule: false,
};

export const LEGACY_STORAGE_KEYS = [
  'gta_assessment_draft_v1',
  'gta_assessment_draft_v2',
  'gta_assessment_draft_v3',
  'gta_assessment_draft_v4',
  'gtaAssessmentDraft_v1',
  'gtaAssessmentDraft_v2',
  'gtaAssessmentDraft_v3',
  'gtaAssessmentDraft_v4',
];

export const createInitialFormData = () => ({
  rank: '',
  timePlayed: '',
  timePlayedDays: '',
  timePlayedHours: '',
  timePlayedMinutes: '',
  timePlayedMode: 'parts',
  liquidCash: '0',
  totalIncomeCollected: '',
  totalRPCollected: '',
  strength: 0,
  flying: 0,
  shooting: 0,
  stealth: 0,
  stamina: 0,
  driving: 0,
  hasKosatka: false,
  hasSparrow: false,
  hasAgency: false,
  dreContractDone: false,
  payphoneUnlocked: false,
  securityContracts: '',
  hasAcidLab: false,
  acidLabUpgraded: false,
  hasNightclub: false,
  nightclubTechs: '',
  nightclubSources: { ...DEFAULT_NIGHTCLUB_SOURCES },
  nightclubFloors: '1',
  nightclubStorage: { ...DEFAULT_NIGHTCLUB_STORAGE },
  hasSalvageYard: false,
  hasTowTruck: false,
  hasSafehouse: false,
  hasRaiju: false,
  hasOppressor: false,
  hasArmoredKuruma: false,
  hasBunker: false,
  bunkerUpgraded: false,
  bunkerEquipmentUpgrade: false,
  bunkerStaffUpgrade: false,
  bunkerSecurityUpgrade: false,
  hasAutoShop: false,
  hasMansion: false,
  mansionType: '',
  hasCarWash: false,
  hasWeedFarm: false,
  hasHeliTours: false,
  sellsToStreetDealers: false,
  dailyStashHouse: false,
  dailyGsCache: false,
  dailySafeCollect: false,
  claimedFreeCar: false,
  claimedWheelSpin: false,
  hasGTAPlus: false,
  playMode: 'invite',
  purchaseDates: { ...DEFAULT_PURCHASE_DATES },
});

export const DEFAULTS = {
  DEFAULT_NIGHTCLUB_SOURCES,
  DEFAULT_NIGHTCLUB_STORAGE,
  DEFAULT_PURCHASE_DATES,
};