export type WorkbookCostBucket = 'businesses' | 'vehicles' | 'upgrades' | 'other';

export type WorkbookItem = {
  id: string;
  label: string;
  cost?: number;
  costText?: string;
  note?: string;
  warning?: boolean;
  bucket?: WorkbookCostBucket;
};

export type WorkbookSection = {
  id: string;
  title: string;
  requirement?: string;
  items: WorkbookItem[];
};

const item = (id: string, label: string, cost?: number, bucket: WorkbookCostBucket = 'other', note?: string, warning = false, costText?: string): WorkbookItem => ({ id, label, cost, bucket, note, warning, costText });
const textItem = (id: string, label: string, note?: string, warning = false): WorkbookItem => ({ id, label, note, warning });

export const financialWorkbookSections: WorkbookSection[] = [
  {
    id: 'A',
    title: 'Section A: Motorcycle Club Businesses',
    requirement: 'Must own a Motorcycle Clubhouse first ($200,000-$495,000).',
    items: [
      textItem('a1_header', 'A1. Cocaine Lockup (Most Profitable MC Business)', 'Production: 210,000 GTA$ / full supply • Time: 2h'),
      item('a1_coke_morningwood', 'Morningwood Cocaine Lockup', 1450000, 'businesses'),
      item('a1_coke_downtown_vinewood', 'Downtown Vinewood Cocaine Lockup', 1350000, 'businesses'),
      item('a1_coke_elysian', 'Elysian Island Cocaine Lockup', 1275000, 'businesses'),
      item('a1_coke_alamo', 'Alamo Sea Cocaine Lockup', 1150000, 'businesses'),
      item('a1_coke_grand_senora', 'Grand Senora Desert Cocaine Lockup', 975000, 'businesses'),
      item('a1_coke_paleto', 'Paleto Bay Cocaine Lockup', 845000, 'businesses'),
      item('a1_coke_upgrade_equipment', 'Cocaine Equipment Upgrade', 1425000, 'upgrades'),
      item('a1_coke_upgrade_staff', 'Cocaine Staff Upgrade', 391500, 'upgrades'),
      item('a1_coke_upgrade_security', 'Cocaine Security Upgrade (Optional)', 351000, 'upgrades'),
      textItem('a2_header', 'A2. Meth Lab (Second Most Profitable)', 'Production: 208,250 GTA$ / full supply • Time: 2h 48m'),
      item('a2_meth_morningwood', 'Morningwood Meth Lab', 1380000, 'businesses'),
      item('a2_meth_downtown_vinewood', 'Downtown Vinewood Meth Lab', 1280000, 'businesses'),
      item('a2_meth_elysian', 'Elysian Island Meth Lab', 1205000, 'businesses'),
      item('a2_meth_alamo', 'Alamo Sea Meth Lab', 1080000, 'businesses'),
      item('a2_meth_grand_senora', 'Grand Senora Desert Meth Lab', 910000, 'businesses'),
      item('a2_meth_paleto', 'Paleto Bay Meth Lab', 780000, 'businesses'),
      item('a2_meth_upgrade_equipment', 'Meth Equipment Upgrade', 1100000, 'upgrades'),
      item('a2_meth_upgrade_staff', 'Meth Staff Upgrade', 331500, 'upgrades'),
      item('a2_meth_upgrade_security', 'Meth Security Upgrade', 297000, 'upgrades'),
      textItem('a3_header', 'A3. Counterfeit Cash Factory', 'Production: 160,766 GTA$ / full supply • Time: 2h 20m'),
      item('a3_cash_morningwood', 'Morningwood Cash Factory', 1205000, 'businesses'),
      item('a3_cash_downtown_vinewood', 'Downtown Vinewood Cash Factory', 1105000, 'businesses'),
      item('a3_cash_elysian', 'Elysian Island Cash Factory', 1030000, 'businesses'),
      item('a3_cash_alamo', 'Alamo Sea Cash Factory', 905000, 'businesses'),
      item('a3_cash_grand_senora', 'Grand Senora Desert Cash Factory', 845000, 'businesses', '40% event discount appears some weeks.'),
      item('a3_cash_paleto', 'Paleto Bay Cash Factory', 650000, 'businesses'),
      item('a3_cash_upgrade_equipment', 'Cash Equipment Upgrade', 977500, 'upgrades'),
      item('a3_cash_upgrade_staff', 'Cash Staff Upgrade', 292500, 'upgrades'),
      item('a3_cash_upgrade_security', 'Cash Security Upgrade', 253500, 'upgrades'),
      textItem('a4_header', 'A4. Weed Farm (Viable with Money Fronts synergy)', 'Production: ~140,000 GTA$ / full supply • Time: 5-6h'),
      item('a4_weed_san_chianski', 'San Chianski Mountain Range Weed Farm', 715000, 'businesses'),
      item('a4_weed_mount_chiliad', 'Mount Chiliad Weed Farm', 805000, 'businesses'),
      item('a4_weed_elysian', 'Elysian Island Weed Farm', 1072500, 'businesses'),
      item('a4_weed_downtown_vinewood', 'Downtown Vinewood Weed Farm', 1358000, 'businesses'),
      item('a4_weed_upgrade_equipment', 'Weed Equipment Upgrade', 990000, 'upgrades'),
      item('a4_weed_upgrade_staff', 'Weed Staff Upgrade', 273000, 'upgrades'),
      item('a4_weed_upgrade_security', 'Weed Security Upgrade', 313500, 'upgrades'),
      textItem('a5_header', 'A5. Document Forgery Office (Avoid)', 'Payback period is worst in class.', true),
      item('a5_documents_any', 'Document Forgery Office (Any Location)', undefined, 'businesses', 'Recommendation: Do not purchase.', true, 'Any Price'),
    ],
  },
  {
    id: 'B',
    title: 'Section B: Money Fronts (2026 DLC)',
    requirement: 'Combined safe income with all three: ~18,500 GTA$ per 48 minutes.',
    items: [
      textItem('b1_header', 'B1. Hands On Car Wash', 'Money laundering hub + safe income.'),
      item('b1_car_wash_la_mesa', 'La Mesa Car Wash', 1000000, 'businesses', '~8,500 GTA$ per 48m safe income.'),
      item('b1_car_wash_burton', 'Burton Car Wash', 1000000, 'businesses', '~8,500 GTA$ per 48m safe income.'),
      item('b1_car_wash_strawberry', 'Strawberry Car Wash (Historical Free Option)', 0, 'businesses', 'Was free during Jan 8-14, 2026 event.', false, 'Free'),
      textItem('b2_header', 'B2. Smoke On The Water Dispensary', 'Boosts Weed Farm +15-20% output.'),
      item('b2_dispensary_vinewood', 'Vinewood Dispensary', 850000, 'businesses', '~5,000 GTA$ per 48m safe income.'),
      item('b2_dispensary_rockford', 'Rockford Hills Dispensary', 850000, 'businesses', '~5,000 GTA$ per 48m safe income.'),
      item('b2_dispensary_del_perro', 'Del Perro Dispensary', 850000, 'businesses', '~5,000 GTA$ per 48m safe income.'),
      textItem('b3_header', 'B3. Higgins Helitours', 'Boosts cargo/hangar ecosystem.'),
      item('b3_helitours_lsia', 'LSIA Helitours', 900000, 'businesses', '~5,000 GTA$ per 48m safe income.'),
      item('b3_helitours_sandy', 'Sandy Shores Helitours', 900000, 'businesses', '~5,000 GTA$ per 48m safe income.'),
    ],
  },
  {
    id: 'C',
    title: 'Section C: Core Businesses',
    items: [
      textItem('c1_header', 'C1. Nightclub', 'Safe: up to 50,000 GTA$ / 48m • Warehouse: up to 1.5M+'),
      item('c1_nightclub_west_vinewood', 'Nightclub - West Vinewood', 1300000, 'businesses'),
      item('c1_nightclub_downtown_vinewood', 'Nightclub - Downtown Vinewood', 1700000, 'businesses'),
      item('c1_nightclub_mission_row', 'Nightclub - Mission Row', 1200000, 'businesses'),
      item('c1_nightclub_cypress', 'Nightclub - Cypress Flats', 1350000, 'businesses'),
      item('c1_nightclub_la_mesa', 'Nightclub - La Mesa', 1500000, 'businesses'),
      item('c1_nightclub_elysian', 'Nightclub - Elysian Island', 1000000, 'businesses'),
      item('c1_nightclub_del_perro', 'Nightclub - Del Perro', 1600000, 'businesses'),
      item('c1_nightclub_vespucci', 'Nightclub - Vespucci Canals', 1400000, 'businesses'),
      item('c1_nightclub_rockford', 'Nightclub - Rockford Hills', 1650000, 'businesses'),
      item('c1_nightclub_upgrade_equipment', 'Nightclub Equipment Upgrade', 1400000, 'upgrades'),
      item('c1_nightclub_upgrade_staff', 'Nightclub Staff Upgrade', 500000, 'upgrades'),
      item('c1_nightclub_upgrade_security', 'Nightclub Security Upgrade', 695000, 'upgrades'),
      item('c1_nightclub_storage', 'Nightclub Storage Floors (max)', 1700000, 'upgrades'),
      textItem('c2_header', 'C2. Bunker (Gunrunning)', 'Production: 210,000 GTA$ / full supply • Time: 2h 20m'),
      item('c2_bunker_chumash', 'Bunker - Chumash', 1650000, 'businesses'),
      item('c2_bunker_route68', 'Bunker - Route 68', 1450000, 'businesses'),
      item('c2_bunker_grand_senora', 'Bunker - Grand Senora Desert', 1550000, 'businesses'),
      item('c2_bunker_farmhouse', 'Bunker - Farmhouse', 2375000, 'businesses'),
      item('c2_bunker_smoke_tree', 'Bunker - Smoke Tree Road', 1850000, 'businesses'),
      item('c2_bunker_paleto', 'Bunker - Paleto Forest', 1200000, 'businesses'),
      item('c2_bunker_raton', 'Bunker - Raton Canyon', 1350000, 'businesses'),
      item('c2_bunker_grapeseed', 'Bunker - Grapeseed', 1425000, 'businesses'),
      item('c2_bunker_upgrade_equipment', 'Bunker Equipment Upgrade', 1670000, 'upgrades'),
      item('c2_bunker_upgrade_staff', 'Bunker Staff Upgrade', 585000, 'upgrades'),
      item('c2_bunker_upgrade_security', 'Bunker Security Upgrade', 420000, 'upgrades'),
      textItem('c3_header', 'C3. Acid Lab', 'Best passive earner by profit/hour.'),
      item('c3_first_dose', 'First Dose Missions (6 missions)', 0, 'other', undefined, false, 'FREE'),
      item('c3_last_dose', 'Last Dose Missions', 0, 'other', undefined, false, 'FREE'),
      item('c3_brickade', 'Brickade 6x6 Truck', 0, 'vehicles', undefined, false, 'FREE'),
      item('c3_acid_upgrade_equipment', 'Acid Lab Equipment Upgrade', 750000, 'upgrades'),
      textItem('c4_header', 'C4. Agency', 'VIP Contracts + Imani Tech unlock path.'),
      item('c4_agency_little_seoul', 'Agency - Little Seoul', 2010000, 'businesses'),
      item('c4_agency_hawick', 'Agency - Hawick', 2130000, 'businesses'),
      item('c4_agency_rockford', 'Agency - Rockford Hills', 2455000, 'businesses'),
      item('c4_agency_vespucci', 'Agency - Vespucci Canals', 2520000, 'businesses'),
      item('c4_agency_upgrade_armory', 'Agency Armory', 615000, 'upgrades'),
      item('c4_agency_upgrade_workshop', 'Agency Vehicle Workshop', 675000, 'upgrades'),
      item('c4_agency_upgrade_accommodation', 'Agency Accommodation', 335000, 'upgrades'),
      textItem('c5_header', 'C5. Arcade', 'Casino Heist + Master Control Terminal'),
      item('c5_arcade_videogeddon', 'Arcade - Videogeddon (La Mesa)', 1985000, 'businesses'),
      item('c5_arcade_eight_bit', 'Arcade - Eight-Bit', 2435000, 'businesses'),
      item('c5_arcade_insert_coin', 'Arcade - Insert Coin (Rockford Hills)', 2245000, 'businesses'),
      item('c5_arcade_wonderama', 'Arcade - Wonderama (Grapeseed)', 1665000, 'businesses'),
      item('c5_arcade_pixel_pete', 'Arcade - Pixel Pete\'s (Paleto Bay)', 1235000, 'businesses'),
      item('c5_arcade_mct', 'Arcade Master Control Terminal', 875000, 'upgrades'),
      item('c5_arcade_games', 'Arcade Games (Optional)', undefined, 'upgrades', undefined, false, '$40,000-$450,000'),
      item('c5_arcade_quarters', 'Arcade Living Quarters', 335000, 'upgrades'),
      item('c5_arcade_security', 'Arcade Security', 595000, 'upgrades'),
    ],
  },
  {
    id: 'D',
    title: 'Section D: Specialized Properties',
    items: [
      textItem('d1_header', 'D1. Vehicle Warehouse', 'Top range export method target: 80,000 GTA$ / car.'),
      item('d1_vehicle_warehouse_la_puerta', 'La Puerta Vehicle Warehouse', 2745000, 'businesses'),
      item('d1_vehicle_warehouse_davis', 'Davis Vehicle Warehouse', 2700000, 'businesses'),
      item('d1_vehicle_warehouse_murrieta', 'Murrieta Heights Vehicle Warehouse', 2640000, 'businesses'),
      item('d1_vehicle_warehouse_elysian', 'Elysian Island Vehicle Warehouse', 2570000, 'businesses'),
      item('d1_vehicle_warehouse_la_mesa', 'La Mesa Vehicle Warehouse', 2495000, 'businesses'),
      item('d1_vehicle_warehouse_el_burro', 'El Burro Heights Vehicle Warehouse', 2380000, 'businesses'),
      textItem('d2_header', 'D2. Large Special Cargo Warehouse', 'Capacity: 111 crates • Full sale: 2.2M GTA$'),
      item('d2_cargo_darnell', 'Darnell Bros Warehouse', 3000000, 'businesses'),
      item('d2_cargo_xero', 'Xero Gas Factory Warehouse', 2800000, 'businesses'),
      item('d2_cargo_logistic', 'Logistic Depot Warehouse', 2700000, 'businesses'),
      item('d2_cargo_bilgeco', 'Bilgeco Warehouse', 2600000, 'businesses'),
      item('d2_cargo_west_vinewood', 'West Vinewood Warehouse', 2500000, 'businesses'),
      item('d2_cargo_cypress', 'Cypress Warehouses', 2300000, 'businesses'),
      textItem('d3_header', 'D3. Auto Shop', 'Contracts: 170k-300k; customer cars add passive.'),
      item('d3_auto_shop_strawberry', 'Auto Shop - Strawberry', 1670000, 'businesses'),
      item('d3_auto_shop_mission_row', 'Auto Shop - Mission Row', 1705000, 'businesses'),
      item('d3_auto_shop_la_mesa', 'Auto Shop - La Mesa', 1790000, 'businesses'),
      item('d3_auto_shop_burton', 'Auto Shop - Burton', 1845000, 'businesses'),
      item('d3_auto_shop_rancho', 'Auto Shop - Rancho', 1920000, 'businesses'),
      item('d3_auto_shop_upgrade_equipment', 'Auto Shop Equipment Upgrade', 745000, 'upgrades'),
      item('d3_auto_shop_upgrade_staff', 'Auto Shop Staff Upgrade', 280000, 'upgrades'),
      textItem('d4_header', 'D4. Salvage Yard', 'Robbery + tow truck passive loop.'),
      item('d4_salvage_murrieta', 'Murrieta Heights Salvage Yard', 2380000, 'businesses'),
      item('d4_salvage_la_puerta', 'La Puerta Salvage Yard', 2420000, 'businesses'),
      item('d4_salvage_cypress', 'Cypress Flats Salvage Yard', 2560000, 'businesses'),
    ],
  },
  {
    id: 'E',
    title: 'Section E: Motorcycle Clubhouse (MC prerequisite)',
    items: [
      item('e_clubhouse_great_chaparral', 'Great Chaparral Clubhouse', 200000, 'businesses'),
      item('e_clubhouse_paleto', 'Paleto Bay Clubhouse', 235000, 'businesses'),
      item('e_clubhouse_grapeseed', 'Grapeseed Clubhouse', 265000, 'businesses'),
      item('e_clubhouse_harmony', 'Harmony Clubhouse', 285000, 'businesses'),
      item('e_clubhouse_sandy', 'Sandy Shores Clubhouse', 315000, 'businesses'),
      item('e_clubhouse_grand_senora', 'Grand Senora Desert Clubhouse', 345000, 'businesses'),
      item('e_clubhouse_la_mesa', 'La Mesa Clubhouse', 375000, 'businesses'),
      item('e_clubhouse_vespucci', 'Vespucci Clubhouse', 395000, 'businesses'),
      item('e_clubhouse_hawick', 'Hawick Clubhouse', 425000, 'businesses'),
      item('e_clubhouse_downtown_vinewood', 'Downtown Vinewood Clubhouse', 455000, 'businesses'),
      item('e_clubhouse_pillbox', 'Pillbox Hill Clubhouse', 465000, 'businesses'),
      item('e_clubhouse_alta', 'Alta Clubhouse', 475000, 'businesses'),
      item('e_clubhouse_burton', 'Burton Clubhouse', 485000, 'businesses'),
      item('e_clubhouse_rockford', 'Rockford Hills Clubhouse', 495000, 'businesses'),
    ],
  },
  {
    id: 'F',
    title: 'Section F: Vehicle Assets (Essential Fleet)',
    items: [
      textItem('f1_header', 'F1. Kosatka + Sparrow'),
      item('f1_kosatka', 'Kosatka Submarine', 2200000, 'vehicles'),
      item('f1_sparrow', 'Sparrow Helicopter', 1815000, 'vehicles'),
      item('f1_missile_bay', 'Kosatka Missile Bay (Optional)', 500000, 'upgrades'),
      item('f1_sonar_station', 'Kosatka Sonar Station (Optional)', 500000, 'upgrades'),
      item('f1_guided_missiles', 'Kosatka Guided Missiles (Optional)', 250000, 'upgrades'),
      textItem('f2_header', 'F2. Terrorbyte + Oppressor Mk II'),
      item('f2_terrorbyte', 'Terrorbyte', 1375000, 'vehicles'),
      item('f2_terrorbyte_workshop', 'Terrorbyte Specialized Workshop', 495000, 'upgrades'),
      item('f2_terrorbyte_drone', 'Terrorbyte Drone Station (Optional)', 860000, 'upgrades'),
      item('f2_oppressor_mk2', 'Oppressor Mk II', 8000000, 'vehicles'),
      item('f2_oppressor_armor', 'Oppressor Mk II Armor Upgrade 100%', 50000, 'upgrades'),
      item('f2_oppressor_countermeasures', 'Oppressor Mk II Countermeasures (Flare)', 110000, 'upgrades'),
      item('f2_oppressor_upgrades', 'Oppressor Mk II upgrades package', 300000, 'upgrades'),
      textItem('f3_header', 'F3. Armored Kuruma'),
      item('f3_armored_kuruma', 'Armored Kuruma', 698000, 'vehicles'),
      item('f3_kuruma_upgrades', 'Kuruma performance upgrades', 258150, 'upgrades'),
      textItem('f4_header', 'F4. Ocelot Virtue (Imani Tech path)'),
      item('f4_virtue_free', 'Ocelot Virtue (from Last Dose missions)', 0, 'vehicles', undefined, false, 'FREE'),
      item('f4_virtue_imani_jammer', 'Imani Tech Missile Lock-On Jammer', 240000, 'upgrades'),
      item('f4_virtue_imani_rc', 'Imani Tech Remote Control Unit', 160000, 'upgrades'),
    ],
  },
  {
    id: 'G',
    title: 'Section G: Recommended Order + Avoid List',
    items: [
      textItem('g_phase1', 'Phase 1: Clubhouse → Acid Lab Upgrade → Kosatka → Sparrow'),
      textItem('g_phase2', 'Phase 2: Nightclub + Upgrades → Coke → Meth'),
      textItem('g_phase3', 'Phase 3: Bunker → Money Fronts → Terrorbyte → Agency'),
      textItem('g_phase4', 'Phase 4: Oppressor Mk II → Arcade + MCT → Vehicle Warehouse'),
      textItem('g_selection_tracker', 'Use this workbook to mark your chosen location per category and track total empire value.'),
      textItem('g_avoid_header', 'Assets to avoid (negative ROI / low priority)', undefined, true),
      textItem('g_avoid_documents', 'Document Forgery Office', undefined, true),
      textItem('g_avoid_arena', 'Arena Workshop', undefined, true),
      textItem('g_avoid_bail', 'Bail Enforcement Office', undefined, true),
      textItem('g_avoid_penthouse', 'Penthouse (Eclipse Towers)', undefined, true),
      textItem('g_avoid_weed_no_synergy', 'Weed Farm without Smoke on the Water synergy', undefined, true),
    ],
  },
];

export const calculateFinancialWorkbookTotals = (selections: Record<string, boolean> = {}) => {
  const selected = financialWorkbookSections.flatMap((section) => section.items).filter((entry) => selections[entry.id]);
  const businesses = selected.filter((entry) => entry.bucket === 'businesses').reduce((sum, entry) => sum + (entry.cost || 0), 0);
  const vehicles = selected.filter((entry) => entry.bucket === 'vehicles').reduce((sum, entry) => sum + (entry.cost || 0), 0);
  const upgrades = selected.filter((entry) => entry.bucket === 'upgrades').reduce((sum, entry) => sum + (entry.cost || 0), 0);
  const other = selected.filter((entry) => entry.bucket === 'other').reduce((sum, entry) => sum + (entry.cost || 0), 0);

  return {
    businesses,
    vehicles,
    upgrades,
    other,
    grandTotal: businesses + vehicles + upgrades + other,
    selectedCount: selected.length,
  };
};
